spring:
  application:
    name: pdf-rag-chatbot

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: gemma3:1b
        options:
          temperature: 0.3

      embedding:
        model: nomic-embed-text

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080